//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JURIS.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.CaseLog = new HashSet<CaseLog>();
        }
    
        public int Id { get; set; }
        public int CaseId { get; set; }
        public Nullable<int> UserProfileId { get; set; }
        public Nullable<int> LawyerId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> RescheduleDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Case Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseLog> CaseLog { get; set; }
    }
}
