//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JURIS.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int Id { get; set; }
        public string SenderUserId { get; set; }
        public string Message { get; set; }
        public string SenderName { get; set; }
        public string SenderImageUrl { get; set; }
        public string ReceipentImageUrl { get; set; }
        public string Link { get; set; }
        public bool IsLink { get; set; }
        public string ReceiverName { get; set; }
        public string ReceipentUserId { get; set; }
        public bool IsRead { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
